### ISSUE TITLE
1.18

### ISSUE THREAD

**Issue by vaporvee** [Dannyn714/BoiledAxolotls#1]
Could you please update this mod? I need this in my life

**Comment by Dannyn714** [comment]
![image](https://github.com/Dannyn714/BoiledAxolotls/assets/30919257/2009970d-3de9-43d3-b0e9-a30de717f98c)
![image](https://github.com/Dannyn714/BoiledAxolotls/assets/30919257/5e2f8dfd-aa3b-4aee-b173-46bb049bdb1f)
just confirmed 1.18 works with fabric api 0.44.0

**Comment by vaporvee** [comment]
lol even forgot i wrote this issue xD

**Comment by Dannyn714** [comment]
> lol even forgot i wrote this issue xD

yeah, I forgot this mod existed for awhile
